"""empty message

Revision ID: 638081ae99fa
Revises: e3fa96b88a15
Create Date: 2020-03-31 20:09:36.399608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638081ae99fa'
down_revision = 'e3fa96b88a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
